version: '3.8'

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: BSCS4AB_PERT-CPM
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: BSCS4AB_PERT-CPM
    depends_on:
      - db

volumes:
  db_data:
