# to run this in docker - please install docker
# https://docs.docker.com/engine/install/
# then run "docker-compose up or docker compose up"

version: '3.8'

services:
  # builds the project - copies entire root directory
  # when this is on a server everywhere with "localhost" in php config should be "app"
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 80:80
    depends_on:
      - db

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 8081:80
      - 443:443

  # built in mysql database
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: waps
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

  # phpmyadmin to view/edit database via ui interface
  # will be available on localhost:8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data:
  caddy_data:
  caddy_config:
