name: Deploy CPM
on:
  push:
    branches: [ development ]
  workflow_dispatch:
env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}
jobs:
  push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Tag latest
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/henry/${{ env.REPO_NAME }}
            git pull
            docker compose build
            docker image prune -f
  run:
    name: Run
    needs: push
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Build Docker Image
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/henry/${{ env.REPO_NAME }}
            docker compose up -d
  prune:
    name: Clean up
    needs: [push, run]
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Clean up
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker container prune -f
            docker image prune -a -f
